apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: mediq
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8090
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HTTP_PORT
              value: "8090"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
          readinessProbe:
            httpGet:
              path: /realms/mediq
              port: 8090
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 10
