apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: mediq
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
