apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
