image: confluentinc/cp-kafka:7.6.0
port: 9092
env:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LOG_RETENTION_HOURS: "168"
