apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: mediq
data:
  DB_URL: "jdbc:postgresql://postgres-service:5432/mediq_users"
  DB_USERNAME: "mediq"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KEYCLOAK_ADMIN_URL: "http://keycloak-service:8090"
  JAEGER_ENDPOINT: "http://jaeger-service:4318/v1/traces"
  ENVIRONMENT: "kubernetes"
