apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: mediq
type: Opaque
# base64("mediq") = bWVkaXE=  |  base64("admin") = YWRtaW4=
data:
  DB_PASSWORD: bWVkaXE=
  KEYCLOAK_ADMIN_SECRET: YWRtaW4=
