apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: mediq
data:
  init.sql: |
    -- mediq_users is already created by POSTGRES_DB env var
    -- Create the remaining 5 service databases

    CREATE DATABASE mediq_doctors;
    GRANT ALL PRIVILEGES ON DATABASE mediq_doctors TO mediq;

    CREATE DATABASE mediq_appointments;
    GRANT ALL PRIVILEGES ON DATABASE mediq_appointments TO mediq;

    CREATE DATABASE mediq_notifications;
    GRANT ALL PRIVILEGES ON DATABASE mediq_notifications TO mediq;

    CREATE DATABASE mediq_emr;
    GRANT ALL PRIVILEGES ON DATABASE mediq_emr TO mediq;

    CREATE DATABASE mediq_analytics;
    GRANT ALL PRIVILEGES ON DATABASE mediq_analytics TO mediq;
