apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mediq
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mediq
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.password }}
            - name: POSTGRES_DB
              value: {{ .Values.database }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.username }}"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.username }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: mediq
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
