apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  namespace: mediq
data:
  krakend.tmpl: |
    {{- .Files.Get "config/krakend.tmpl" | nindent 4 }}
  krakend.json: |
    {{- .Files.Get "config/krakend.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-partials
  namespace: mediq
data:
  auth_doctor_admin.tmpl: |
    {{- .Files.Get "config/partials/auth_doctor_admin.tmpl" | nindent 4 }}
  auth_doctor_nurse_admin.tmpl: |
    {{- .Files.Get "config/partials/auth_doctor_nurse_admin.tmpl" | nindent 4 }}
  circuit_breaker.tmpl: |
    {{- .Files.Get "config/partials/circuit_breaker.tmpl" | nindent 4 }}
  endpoint_users.tmpl: |
    {{- .Files.Get "config/partials/endpoint_users.tmpl" | nindent 4 }}
  endpoint_patients.tmpl: |
    {{- .Files.Get "config/partials/endpoint_patients.tmpl" | nindent 4 }}
  endpoint_referrals.tmpl: |
    {{- .Files.Get "config/partials/endpoint_referrals.tmpl" | nindent 4 }}
  endpoint_doctors.tmpl: |
    {{- .Files.Get "config/partials/endpoint_doctors.tmpl" | nindent 4 }}
  endpoint_appointments.tmpl: |
    {{- .Files.Get "config/partials/endpoint_appointments.tmpl" | nindent 4 }}
  endpoint_payments.tmpl: |
    {{- .Files.Get "config/partials/endpoint_payments.tmpl" | nindent 4 }}
  endpoint_emr.tmpl: |
    {{- .Files.Get "config/partials/endpoint_emr.tmpl" | nindent 4 }}
  endpoint_analytics.tmpl: |
    {{- .Files.Get "config/partials/endpoint_analytics.tmpl" | nindent 4 }}
  endpoint_notifications.tmpl: |
    {{- .Files.Get "config/partials/endpoint_notifications.tmpl" | nindent 4 }}
  rate_limit_proxy.tmpl: |
    {{- .Files.Get "config/partials/rate_limit_proxy.tmpl" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-settings
  namespace: mediq
data:
  hosts.json: |
    {{- .Files.Get "config/settings/hosts.json" | nindent 4 }}
