apiVersion: v1
kind: Service
metadata:
  name: krakend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
