releases:
  - name: mediq-krakend
    chart: ./helm/gateway/krakend
    namespace: mediq
    needs:
      - mediq/mediq-user-service
      - mediq/mediq-doctor-service
      - mediq/mediq-appointment-service
      - mediq/mediq-keycloak
    values:
      - ./helm/gateway/krakend/values.yaml
    set:
      - name: replicaCount
        value: '{{ .Environment.Values.krakend.replicas | default 1 }}'
