package com.mediq.emr.model;

public enum EmrEventType {
    DIAGNOSIS_ADDED,
    DIAGNOSIS_RESOLVED,
    MEDICATION_PRESCRIBED,
    MEDICATION_DISCONTINUED,
    ALLERGY_RECORDED,
    ALLERGY_REMOVED,
    LAB_RESULT_RECORDED,
    VITAL_SIGNS_RECORDED,
    PROCEDURE_PERFORMED,
    VISIT_RECORDED,
    REFERRAL_ISSUED,
    EMERGENCY_ALERT
}
